FROM debian:bullseye-slim
LABEL maintainer="Khulnasoft Inc"
LABEL khulnasoft.role=system

ENV CHECKPOINT_DISABLE=true \
    DF_TLS_ON="1" \
    MGMT_CONSOLE_PORT=443 \
    DF_KUBERNETES_ON="Y" \
    MGMT_CONSOLE_URL_SCHEMA=https \
    KHULNASOFT_KEY="" \
    MGMT_CONSOLE_URL_INTERNAL=127.0.0.1 \
    MGMT_CONSOLE_PORT_INTERNAL=8081 \
    DF_ENABLE_CLUSTER_DISCOVERY="true"

WORKDIR /home/khulnasoft
RUN apt-get update
RUN apt-get install -y --no-install-recommends libpcap0.8 bash conntrack iproute2 util-linux curl grep tar git wget supervisor gettext htop vim ca-certificates sudo cron logrotate
RUN /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/v0.20.12/install.sh)"
RUN useradd -rm -d /home/khulnasoft -s /bin/bash -g root -G sudo -u 1001 khulnasoft

COPY etc/fenced_logrotate.conf /etc/logrotate.d/fenced_logrotate.conf

COPY start_agent.sh /usr/local/bin/start_agent
RUN chmod +x /usr/local/bin/start_agent
COPY plugins/khulnasoft_shipper/khulnasoft_shipper /home/khulnasoft/bin/shipper
COPY plugins/khulnasoft_shipper/routes.yaml /home/khulnasoft/routes.yaml

WORKDIR /opt/steampipe
COPY tools/apache/scope/probe/kubernetes/kubeconfig /home/khulnasoft/.kube/config
COPY tools/apache/scope/probe/kubernetes/token.sh /home/khulnasoft/token.sh
RUN chown -R khulnasoft:root /opt/ /home/khulnasoft /var/log /var/run/

USER khulnasoft
COPY supervisord-cluster.conf /home/khulnasoft/supervisord.conf
COPY run_discovery.sh /home/khulnasoft/
COPY plugins/etc/run_shipper.sh /home/khulnasoft/
RUN steampipe plugin install steampipe \
    && steampipe plugin install kubernetes \
    && git clone https://github.com/turbot/steampipe-mod-kubernetes-compliance.git

COPY tools/apache/scope/docker/discovery /home/khulnasoft/
COPY khulnasoftd /bin/khulnasoftd

USER root

RUN chmod +x /home/khulnasoft/*.sh /home/khulnasoft/discovery

ENTRYPOINT ["/usr/local/bin/start_agent"]
