{{- if .Values.fileserver.create }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "khulnasoft-console.fullname" . }}-file-server-secret
  labels:
    {{- include "khulnasoft-console.labels" . | nindent 4 }}
    name: {{ include "khulnasoft-console.fullname" . }}-file-server-secret
stringData:
    {{- range $k, $v := .Values.fileserver.secrets }}
    {{ $k }}: {{ $v }}
    {{- end }}
{{- end }}