---
{{- if eq "true" .Values.createKhulnasoftKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: khulnasoft-key
  labels:
    app: khulnasoft
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- if .Values.khulnasoftKey }}
  khulnasoft-key: "{{ .Values.khulnasoftKey | b64enc }}"
{{- else }}
  khulnasoft-key: ""
{{- end }}
{{- end }}
---