#!/bin/bash

env PGPASSWORD="$KHULNASOFT_POSTGRES_USER_DB_PASSWORD" psql "host=$KHULNASOFT_POSTGRES_USER_DB_HOST port=$KHULNASOFT_POSTGRES_USER_DB_PORT user=$KHULNASOFT_POSTGRES_USER_DB_USER dbname=$KHULNASOFT_POSTGRES_USER_DB_NAME sslmode=$KHULNASOFT_POSTGRES_USER_DB_SSLMODE" < $1

echo "Postgres restore completed from the file pg_data.dump"
