---
{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "khulnasoft-agent.imagePullSecretName" . }}
  labels:
    {{- include "khulnasoft-agent.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ template "imagePullSecret" . }}"
{{- end }}
---
{{- if .Values.createKhulnasoftKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "khulnasoft-agent.fullname" . }}-key
  labels:
    {{- include "khulnasoft-agent.labels" . | nindent 4 }}
type: Opaque
data:
  khulnasoft-key: {{ required "khulnasoftKey is required" .Values.khulnasoftKey | b64enc }}
{{- end }}
