{{- if .Values.postgres.create }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "khulnasoft-console.fullname" . }}-postgres-secret
  labels:
    {{- include "khulnasoft-console.labels" . | nindent 4 }}
    name: {{ include "khulnasoft-console.fullname" . }}-postgres-secret
stringData:
    {{- range $k, $v := .Values.postgres.secrets }}
    {{ $k }}: {{ $v }}
    {{- end }}
{{- end }}