{{- if .Values.neo4j.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "khulnasoft-console.fullname" . }}-neo4j-config
  labels:
    {{- include "khulnasoft-console.labels" . | nindent 4 }}
    name: {{ include "khulnasoft-console.fullname" . }}-neo4j-config
data:
  {{- range $k, $v := .Values.neo4j.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}