{{- if .Values.neo4j.create }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "khulnasoft-console.fullname" . }}-neo4j-secret
  labels:
    {{- include "khulnasoft-console.labels" . | nindent 4 }}
    name: {{ include "khulnasoft-console.fullname" . }}-neo4j-secret
stringData:
    {{- range $k, $v := .Values.neo4j.secrets }}
    {{ $k }}: {{ $v }}
    {{- end }}
{{- end }}