apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "khulnasoft-console.fullname" . }}-ingester
  labels:
    {{- include "khulnasoft-console.labels" . | nindent 4 }}
    name: {{ include "khulnasoft-console.fullname" . }}-ingester
spec:
  {{- if not .Values.ingester.autoscaling.enabled }}
  replicas: {{ .Values.ingester.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "khulnasoft-console.selectorLabels" . | nindent 6 }}
      name: {{ include "khulnasoft-console.fullname" . }}-ingester
  template:
    metadata:
      {{- with .Values.ingester.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "khulnasoft-console.selectorLabels" . | nindent 8 }}
        name: {{ include "khulnasoft-console.fullname" . }}-ingester
        {{- with .Values.ingester.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "khulnasoft-console.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ingester.podSecurityContext | nindent 8 }}
      containers:
        - name: ingester
          securityContext:
            {{- toYaml .Values.ingester.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRepoPrefix }}/{{ .Values.ingester.image.repository }}:{{ default .Values.global.imageTag .Values.ingester.image.tag }}"
          imagePullPolicy: {{ .Values.ingester.image.pullPolicy }}
          env:
            - name: KHULNASOFT_MODE
              value: ingester
          envFrom:
            - configMapRef:
                name: "{{ include "khulnasoft-console.fullname" . }}-config"
            - secretRef:
                {{- if .Values.redis.create }}
                name: "{{ include "khulnasoft-console.fullname" . }}-secrets-redis"
                {{- else }}
                name: {{ .Values.redis.secretName }}
                {{- end }}
            - secretRef:
                {{- if or .Values.fileserver.create .Values.aws_s3_buckets.create }}
                name: "{{ include "khulnasoft-console.fullname" . }}-secrets-fileserver"
                {{- else if .Values.fileserver.secretName }}
                name: {{ .Values.fileserver.secretName }}
                {{- else if .Values.aws_s3_buckets.secretName }}
                name: {{ .Values.aws_s3_buckets.secretName }}
                {{- end }}
            - secretRef:
                {{- if .Values.kafka.create }}
                name: "{{ include "khulnasoft-console.fullname" . }}-secrets-kafka"
                {{- else }}
                name: {{ .Values.kafka.secretName }}
                {{- end }}
            - secretRef:
                {{- if .Values.postgres.create }}
                name: "{{ include "khulnasoft-console.fullname" . }}-secrets-postgres"
                {{- else }}
                name: {{ .Values.postgres.secretName }}
                {{- end }}
            - secretRef:
                {{- if .Values.neo4j.create }}
                name: "{{ include "khulnasoft-console.fullname" . }}-secrets-neo4j"
                {{- else }}
                name: {{ .Values.neo4j.secretName }}
                {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.ingester.resources | nindent 12 }}
      {{- with .Values.ingester.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingester.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingester.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "khulnasoft-console.fullname" . }}-ingester
  labels:
    {{- include "khulnasoft-console.labels" . | nindent 4 }}
    name: {{ include "khulnasoft-console.fullname" . }}-ingester
spec:
  type: {{ .Values.ingester.service.type }}
  ports:
    - port: {{ .Values.ingester.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "khulnasoft-console.selectorLabels" . | nindent 4 }}
    name: {{ include "khulnasoft-console.fullname" . }}-ingester
---
{{- if .Values.ingester.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "khulnasoft-console.fullname" . }}-ingester
  labels:
    {{- include "khulnasoft-console.labels" . | nindent 4 }}
    component: ingester
    name: khulnasoft-ingester
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: khulnasoft-ingester
  minReplicas: {{ .Values.ingester.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.ingester.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.ingester.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.ingester.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.ingester.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.ingester.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}