{{- if .Values.fileserver.create }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "khulnasoft-console.fullname" . }}-secrets-fileserver
  labels:
    {{- include "khulnasoft-console.labels" . | nindent 4 }}
    component: file-server
stringData:
  KHULNASOFT_FILE_SERVER_HOST: {{ include "khulnasoft-console.fullname" . }}-file-server.{{ .Release.Namespace }}.svc.{{ .Values.global.cluster_domain }}
  KHULNASOFT_FILE_SERVER_PORT: "9000"
  KHULNASOFT_FILE_SERVER_SECURE: "false"
  KHULNASOFT_FILE_SERVER_BUCKET: default
  {{- if .Values.fileserver.secrets }}
  KHULNASOFT_FILE_SERVER_PASSWORD: {{ .Values.fileserver.secrets.FILE_SERVER_ROOT_PASSWORD | quote }}
  KHULNASOFT_FILE_SERVER_USER: {{ .Values.fileserver.secrets.FILE_SERVER_ROOT_USER | quote }}
  {{- end }}
  KHULNASOFT_FILE_SERVER_DB_BUCKET: database
{{- end }}

