{{- if .Values.redis.create }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "khulnasoft-console.fullname" . }}-secrets-redis
  labels:
    {{- include "khulnasoft-console.labels" . | nindent 4 }}
    component: redis
stringData:
  KHULNASOFT_REDIS_DB_NUMBER: "0"
  KHULNASOFT_REDIS_PORT: "6379"
  KHULNASOFT_REDIS_HOST: {{ include "khulnasoft-console.fullname" . }}-redis.{{ .Release.Namespace }}.svc.{{ .Values.global.cluster_domain }}
{{- end }}
